# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, trial ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
#    - name: Set up selenium firefox
#      container:
#        image: selenium/standalone-firefox:latest
#    - name: Install google chrome
#      run: |
#        whatis flatpak
#        chmod +x ./scripts/InstallChrome.sh
#         ./scripts/InstallChrome.sh
    - name: Build with Maven
      run: mvn -B package --file pom.xml -X
# will need build job -> build job simultaneously take care of testing
# find a way to push to master
  integration:
    needs: build
    runs-on: ubuntu-latest
    # checkout what was commited, then create the pr
    # accept the pr and merge to master
    steps:
    - uses: actions/checkout@v2
    - name: create pr, accept and merge to master
      id: cpr
      uses: peter-evans/create-pull-request@v3
      # with:
        # token: ${{ secrets.GITHUB_TOKEN }}
        # labels: |
          # automerge
    - name: check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
    - name: branch name
      run: |
        echo "running on branch - ${{ github.ref }}"
        echo "different thing: - ${{ github.base_ref }}"
        echo "different thing: - ${{ github.head_ref }}"
        echo "actor: - ${{ github.actor }}"
    # - uses: pascalgn/automerge-action@v0.12.0
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # if we were to make any changes it would be here
    # https://github.com/marketplace/actions/create-pull-request
    # following works on prs with the auto merge label
    # https://github.com/marketplace/actions/merge-pull-requests  
  #     run: pwd
      # with:
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        # branch: ${{ github.ref }}
    
    # find out a way to push to master